### **FUNÇÕES E MODULARIZAÇÃO**

In [2]:
def saudacao():
    print("Olá!")

In [3]:
saudacao()

Olá!

In [4]:
# pensar em uma função como uma receita.

def preparar_cafe():
    print("Aquecer a água")
    print("Colocar o café")
    print("Adicionar a água")
    print("Servir o café")

In [5]:
preparar_cafe()

Aquecer a água
Colocar o café
Adicionar a água
Servir o café

#### Parâmetros: passando dados para uma função

In [6]:
def apresentar_base(nome):
    print("Base analisada:", nome)

In [7]:
apresentar_base("Vendas 2026")

Base analisada: Vendas 2026

In [8]:
# Uma função pode receber vários parâmetros

def calcular_vendas(preco, quantidade):
    total = preco * quantidade
    print(total)

In [9]:
calcular_vendas(3500, 8)

28000

#### O que é return?

In [10]:
def calcular_positividade(positivos, exames):
    percentual = positivos / exames * 100
    return percentual

In [11]:
resultado = calcular_positividade(120, 1000)

print(resultado)

12.0

In [13]:
# Não precisamos obrigatoriamente criar uma variável dentro da função.

def calcular_total(preco, quantidade):
    total = preco * quantidade
    return total



def calcular_total(preco, quantidade):
    return preco * quantidade

In [14]:
total = calcular_total(3500, 8)

print(total)

28000

In [20]:
# Exemplo com filtragem de dados

# Queremos somente vendas acima de determinado valor:

def filtrar_vendas(vendas, minimo):
    resultado = []

    for venda in vendas:
        if venda >= minimo:
            resultado.append(venda) # adicionando valores a lista

    return resultado

In [21]:
vendas = [1200, 500, 2300, 800, 3100]

vendas_filtradas = filtrar_vendas(vendas, 1000)

print(vendas_filtradas)

[1200, 2300, 3100]

#### Parâmetros nomeados

In [22]:
# Também podemos identificar explicitamente cada argumento na chamada:

def calcular_total(preco, quantidade):
    return preco * quantidade


calcular_total(3500, 8)

28000

In [24]:
#calcular_total(preco=3500, quantidade=8)

calcular_total(quantidade=8, preco=3500)

28000

#### Parâmetro com valor padrão

##### Esse formato pode deixar códigos maiores mais legíveis.

In [25]:
# Também podemos definir um valor padrão:

def calcular_comissao(vendas, percentual=0.05):
    comissao = vendas * percentual
    return comissao

In [28]:
#calcular_comissao(10000)

#calcular_comissao(10000, 0.1)

calcular_comissao(10000, percentual = 0.2)

2000.0

#### *args permite que uma função receba uma quantidade variável de argumentos posicionais.

In [29]:
def somar(*args):
    print(args)

In [31]:
somar(10, 20, 30, 40, 50)

(10, 20, 30, 40, 50)

In [32]:
# imagine que queremos calcular a média de várias vendas

def calcular_media(*vendas):

    media = sum(vendas) / len(vendas)

    return media

In [34]:
media = calcular_media(
    1200,
    1500,
    1800,
    2100,
    500
)

print(media)

#*args recebe vários argumentos posicionais e os reúne em uma tupla.
#o nome args é apenas uma convenção.

1420.0

#### **kwargs - permite receber uma quantidade variável de argumentos nomeados.

In [35]:
def mostrar_dados(**kwargs):
    print(kwargs)

In [36]:
mostrar_dados(
    nome = "Maria",
    peso = 65,
    altura = 1.68
)

# Aqui os dados são armazenados em um dicionário.
# A documentação oficial do Python especifica
# que um parâmetro **nome recebe os argumentos
# nomeados adicionais em forma de dicionário.

{'nome': 'Maria', 'peso': 65, 'altura': 1.68}

In [37]:
def mostrar_registro(**dados):

    for chave, valor in dados.items():
        print(chave, ":", valor)

In [38]:
mostrar_registro(
    nome = "Maria da Silva",
    idade = 35,
    cidade = "Recife"
)

nome : Maria da Silva
idade : 35
cidade : Recife

#### Função lambda

In [39]:
# Uma função tradicional pode ser escrita assim

def dobrar(valor):
    return valor * 2

resultado = dobrar(10)

print(resultado)

20

In [40]:
dobrar = lambda valor: valor * 2

print(dobrar(10))

20

In [43]:
#acrescentar 10%
aumentar = lambda valor: valor * 1.10

print(aumentar(1000))

1100.0

#### Exemplo lambda com tabelas

In [44]:
import pandas as pd

dados = {
    "produto": ["Notebook", "Monitor", "Mouse"],
    "preco": [3500, 1200, 150],
    "quantidade": [2, 3, 10]
}

df = pd.DataFrame(dados)

df

    produto  preco  quantidade
0  Notebook   3500           2
1   Monitor   1200           3
2     Mouse    150          10

In [45]:
df["preco_novo"] = df["preco"].apply(lambda valor: valor * 1.10)

display(df)

    produto  preco  quantidade  preco_novo
0  Notebook   3500           2      3850.0
1   Monitor   1200           3      1320.0
2     Mouse    150          10       165.0

In [46]:
df["faturamento"] = df.apply(
    lambda linha: linha["preco"] * linha["quantidade"], axis = 1)

df

    produto  preco  quantidade  preco_novo  faturamento
0  Notebook   3500           2      3850.0         7000
1   Monitor   1200           3      1320.0         3600
2     Mouse    150          10       165.0         1500

In [47]:
dados = {
    "produto": [
        "  notebook ",
        "MONITOR   ",
        "   mouse"
    ],
    "preco": [3500, 1200, 150]
}

df = pd.DataFrame(dados)

df

       produto  preco
0    notebook    3500
1   MONITOR      1200
2        mouse    150

In [48]:
df["produto"] = df["produto"].apply(lambda texto:
                                     texto.strip().upper())

df

    produto  preco
0  NOTEBOOK   3500
1   MONITOR   1200
2     MOUSE    150

In [ ]:
# Lambda com uma condição

df["categoria"] = (df["preco"]
                   .apply(lambda valor:
                     "ALTO" if valor >= 1000 else "BAIXO"))

df

    produto  preco categoria
0  NOTEBOOK   3500      ALTO
1   MONITOR   1200      ALTO
2     MOUSE    150     BAIXO

In [52]:
# lambda com mais de um parâmetro

calcular_total = lambda preco, quantidade: preco * quantidade

resultado = calcular_total(3500, 2)

print(resultado)

7000

#### Unindo lambda + tratamento de dados

In [53]:
dados = {
    "nome": [
        "   maria     da silva ",
        "joão    pereira   ",
        "   ana    souza"
    ],
    "peso": [65, 82, 58],
    "altura": [1.68, 1.80, 1.62]
}

df = pd.DataFrame(dados)

df

                     nome  peso  altura
0     maria     da silva     65    1.68
1      joão    pereira       82    1.80
2            ana    souza    58    1.62

In [54]:
import re

df["nome"] = df["nome"].apply(
    lambda nome: re.sub(r"\s+", " ", nome).strip().upper()
)

df

             nome  peso  altura
0  MARIA DA SILVA    65    1.68
1    JOÃO PEREIRA    82    1.80
2       ANA SOUZA    58    1.62

#### O que é um módulo?

In [55]:
from math import sqrt, ceil, floor

print(sqrt(25))
print(ceil(4.2))
print(floor(4.8))

5.0
5
4

##### Vamos criar dois arquivos

In [56]:
import funcoes_dados

In [57]:
vendas = [1000, 1500, 2000, 2500]

media = funcoes_dados.calcular_media(vendas)

print(media)

1750.0

In [58]:
# Podemos importar apenas a função

from funcoes_dados import calcular_media

In [59]:
vendas = [1000, 1500, 2000, 2500]

media = calcular_media(vendas)

print(media)

1750.0

In [60]:
# outro arquivo tratamento

import pandas as pd

from tratamento import tratar_nome, remover_acentos

In [61]:
dados = {
    "nome": [
        "   maria     da silva ",
        "joão    pereira   ",
        "   ana    souza"
    ],

    "peso": [65, 82, 58],

    "altura": [1.68, 1.80, 1.62]
}

df = pd.DataFrame(dados)

df

                     nome  peso  altura
0     maria     da silva     65    1.68
1      joão    pereira       82    1.80
2            ana    souza    58    1.62

In [62]:
df["nome"] = df["nome"].apply(tratar_nome)

df

             nome  peso  altura
0  MARIA DA SILVA    65    1.68
1    JOÃO PEREIRA    82    1.80
2       ANA SOUZA    58    1.62

In [63]:
df["nome"] = df["nome"].apply(remover_acentos)

df

             nome  peso  altura
0  MARIA DA SILVA    65    1.68
1    JOAO PEREIRA    82    1.80
2       ANA SOUZA    58    1.62

#### from modulo import *

In [ ]:
from tratamento import *

Isso pode importar diversos nomes do módulo.

Porém, não é uma prática recomendada na maior parte dos programas,

porque deixa menos claro de onde cada nome veio e pode provocar conflitos entre nomes. 

A própria documentação oficial observa que import * geralmente é evitado por tornar o código menos legível e poder ocultar nomes já definidos.

In [ ]:
import tratamento

# ou

from tratamento import tratar_nome

#### if __name__ == "__main__"

In [64]:
import calculos

vendas = [1000, 1500, 2000]

print(calcular_media(vendas))

#Isso acontece porque instruções no nível superior de um módulo são executadas quando ele é importado pela primeira vez.

1500.0
1500.0

In [ ]:
import calculos_corr

vendas = [1000, 1500, 2000]

print(calcular_media(vendas))

1500.0

#### outro exemplo

In [ ]:
import conversor

preco_produto = conversor.dolar_para_real(50)
print(f"Preço na loja: R$ {preco_produto}")

Ele importa o conversor.

Como o if __name__ == "__main__": está lá, o Python pula o modo de teste e não polui a tela da sua loja com mensagens desnecessárias.