## PANDAS

### Séries

In [1]:
import pandas as pd

idades = pd.Series([25, 32, 41, 29])

print(idades)

0    25
1    32
2    41
3    29
dtype: int64

In [2]:
# Podemos criar nossos próprios índices.

import pandas as pd

idades = pd.Series(
    [25, 32, 41, 29],
    index=["Ana", "Bruno", "Carlos", "Daniela"]
)

print(idades)

Ana        25
Bruno      32
Carlos     41
Daniela    29
dtype: int64

In [3]:
# Acessando um valor da Series
# A ideia é semelhante a acessar um valor de um dicionário Python.

print(idades["Bruno"])

32

In [4]:
# Fazendo operações

print(idades.mean())

print(idades.sum())

print(idades.min())

print(idades.max())

print(idades.count())

31.75
127
25
41
4

In [5]:
idades * 2

Ana        50
Bruno      64
Carlos     82
Daniela    58
dtype: int64

### DataFrame

In [6]:
import pandas as pd

dados = {
    "nome": ["Ana", "Bruno", "Carlos"],
    "idade": [25, 32, 41],
    "cidade": ["Joinville", "Florianópolis", "Blumenau"]
}

df_pessoas = pd.DataFrame(dados)

print(df_pessoas)

     nome  idade         cidade
0     Ana     25      Joinville
1   Bruno     32  Florianópolis
2  Carlos     41       Blumenau

### COLUNAS ↓

| ÍNDICE | nome   | idade | cidade      |
|:------:|--------|:-----:|-------------|
| **0**  | Ana    | 25    | Joinville      |
| **1**  | Bruno  | 32    | Florianópolis |
| **2**  | Carlos | 41    | Blumenau       |

- **DataFrame**
  - tabela
  - composto por:
    - **Series** → `nome`
    - **Series** → `idade`
    - **Series** → `cidade`

#### Exemplos

In [7]:
import pandas as pd

dados = {
    "produto": ["Notebook", "Mouse", "Teclado", "Monitor"],
    "quantidade": [2, 10, 5, 3],
    "preco": [3500, 80, 150, 900]
}

df_vendas = pd.DataFrame(dados)

df_vendas

    produto  quantidade  preco
0  Notebook           2   3500
1     Mouse          10     80
2   Teclado           5    150
3   Monitor           3    900

In [8]:
# Agora podemos criar uma nova coluna
# não exige um for explícito linha por linha.

df_vendas["total"] = df_vendas["quantidade"] * df_vendas["preco"]

df_vendas

    produto  quantidade  preco  total
0  Notebook           2   3500   7000
1     Mouse          10     80    800
2   Teclado           5    150    750
3   Monitor           3    900   2700

#### Leitura diferentes fontes

In [9]:
#url = "https://docs.google.com/spreadsheets/d/1mph6Xr-_jca41Lt4P2xXA0oUm_YcSYYrB3ON40665xU/edit?usp=sharing"

# Mudamos o final da URL de "/edit?usp=sharing" para "/export?format=xlsx"
url = "https://docs.google.com/spreadsheets/d/1mph6Xr-_jca41Lt4P2xXA0oUm_YcSYYrB3ON40665xU/export?format=xlsx"

perfil_alunos = pd.read_excel(url)

#perfil_alunos = pd.read_excel(url, engine = "openpyxl")

display(perfil_alunos)

,Carimbo de data/hora,Seu gênero:,Idade:,Você atua na área de dados?,Nível de instrução formal:,Pereferência de atuação na área de dados:
0,2026-09-09 20:55:33.672,Feminino,45,Não,Mestrado,Híbrido
1,2026-09-09 20:55:58.292,Masculino,26,Não,Estudante de graduação,Remoto
2,2026-09-09 20:56:06.836,Masculino,50,Não,Pós Graduação,Híbrido
3,2026-09-09 20:56:08.479,Feminino,29,Não,Não tenho Graduação,Remoto
4,2026-09-09 20:56:22.244,Masculino,50,Sim,Pós Graduação,Remoto
5,2026-09-09 20:57:25.738,Masculino,56,Não,Graduação,Remoto
6,2026-09-09 20:57:28.162,Masculino,27,Não,Estudante de graduação,Remoto
7,2026-09-09 20:57:33.920,Feminino,44,Não,Estudante de graduação,Remoto
8,2026-09-09 20:57:37.882,Masculino,64,Não,Graduação,Remoto
9,2026-09-09 20:58:02.932,Masculino,77,Sim,Mestrado,Remoto
10,2026-09-09 20:58:37.020,Masculino,34,Não,Pós Graduação,Híbrido
11,2026-09-09 21:00:04.990,Feminino,39,Não,Pós Graduação,Remoto
12,2026-09-09 21:01:24.245,Feminino,33,Não,Graduação,Híbrido
13,2026-09-09 21:01:29.785,Masculino,64,Sim,Não tenho Graduação,Remoto
14,2026-09-09 21:01:33.053,Feminino,49,Não,Doutorado,Remoto
15,2026-09-09 21:01:46.373,Masculino,29,Não,Pós Graduação,Híbrido
16,2026-09-09 21:01:56.874,Feminino,46,Não,Graduação,Híbrido
17,2026-09-09 21:02:06.593,Masculino,46,Sim,Estudante de graduação,Híbrido
18,2026-09-09 21:02:13.953,Masculino,40,Não,Graduação,Remoto
19,2026-09-09 21:02:41.605,Masculino,31,Não,Mestrado,Remoto
20,2026-09-09 21:04:03.753,Feminino,36,Não,Graduação,Remoto
21,2026-09-09 21:57:11.372,Masculino,43,Não,Pós Graduação,Híbrido

Uma API (Interface de Programação de Aplicações) é uma ponte que permite a comunicação direta entre dois sistemas diferentes.

No seu exemplo da API do Banco Central:

• O seu código faz um pedido (requisição) enviando uma URL com parâmetros (como as datas desejadas).

• O servidor do Banco Central processa o pedido e devolve uma resposta automática com os dados brutos estruturados (em formato json).

In [10]:
import requests
import pandas as pd

dataInicial = '01/01/2026'
dataFinal = '31/12/2026'

# 188 – INPC
# 189 – IGP‑M
# 190 – IGP‑DI
# 433 - IPCA
# 7478 – IPCA‑15
# 10764 – IPCA‑E

url = f'https://api.bcb.gov.br/dados/serie/bcdata.sgs.433/dados?formato=json&dataInicial={dataInicial}&dataFinal={dataFinal}'

response = requests.get(url)
dados = response.json()

df_ipca = pd.DataFrame(dados)

df_ipca

         data  valor
0  01/01/2026   0.33
1  01/02/2026   0.70
2  01/03/2026   0.88
3  01/04/2026   0.67
4  01/05/2026   0.58
5  01/06/2026   0.16
6  01/07/2026   0.07
7  01/08/2026  -0.32
8  01/09/2026   0.82

#### Leitura e inspeção dos dados

In [ ]:
df_base_varejo = pd.read_csv("base_varejo.csv", sep = ";")

df_base_varejo

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
0,30/12/2020,458503,818,F,2,0,B,124,LIMPEZA,TIRA LIMO
1,06/10/2019,105930,991,F,2,2,C,217,ALIMENTOS,BISCOITO
2,04/05/2022,808343,772,F,2,0,B,174,LIMPEZA,LIMPADOR PERFUMADO
3,16/06/2020,340312,455,F,2,0,C,159,ALIMENTOS,PAO DE FORMA
4,07/09/2021,610633,601,M,4,0,A,208,HIGIENE,CONDICIONADOR
...,...,...,...,...,...,...,...,...,...,...
995,11/12/2020,426609,125,M,3,0,B,120,LIMPEZA,VASSOURA
996,18/03/2022,800136,402,M,2,0,C,4,ALIMENTOS,ABACAXI
997,24/02/2022,777197,517,F,3,1,B,143,BEBIDAS,REFRIGERANTE GUARANA
998,05/07/2021,567496,199,M,3,3,B,124,LIMPEZA,TIRA LIMO
999,04/01/2020,284666,612,F,3,4,B,228,LIMPEZA,AMACIANTE

In [22]:
df_vendas = pd.read_excel("vendas.xlsx")

df_vendas

,id_venda,data_venda,id_produto,produto,categoria,quantidade,preco_unitario,desconto_pct,municipio,regiao_sc,vendedor,canal_venda,forma_pagamento,tipo_cliente,valor_bruto,valor_desconto,valor_liquido
0,V001,2026-08-01,P001,Notebook Pro 15,Informática,2,3899.9,0.05,Florianópolis,Grande Florianópolis,Ana Souza,Loja Física,Cartão de Crédito,Pessoa Física,7799.8,389.990,7409.810
1,V002,2026-08-02,P003,Mouse Sem Fio,Periféricos,8,119.9,0.00,Joinville,Norte,Bruno Lima,Online,PIX,Pessoa Física,959.2,0.000,959.200
2,V003,2026-08-03,P004,Teclado Mecânico,Periféricos,4,289.9,0.10,Blumenau,Vale do Itajaí,Carla Mendes,Loja Física,Cartão de Crédito,Pessoa Jurídica,1159.6,115.960,1043.640
3,V004,2026-08-04,P002,Monitor 24,Informática,3,899.9,0.05,Chapecó,Oeste,Diego Martins,Representante,Boleto,Pessoa Jurídica,2699.7,134.985,2564.715
4,V005,2026-08-05,P005,Headset USB,Periféricos,5,179.9,0.00,Criciúma,Sul,Eduarda Alves,Online,PIX,Pessoa Física,899.5,0.000,899.500
5,V006,2026-08-06,P006,Webcam Full HD,Periféricos,6,249.9,0.08,Itajaí,Vale do Itajaí,Ana Souza,Online,Cartão de Crédito,Pessoa Jurídica,1499.4,119.952,1379.448
6,V007,2026-08-07,P007,SSD 1TB,Informática,4,459.9,0.03,São José,Grande Florianópolis,Bruno Lima,Loja Física,PIX,Pessoa Física,1839.6,55.188,1784.412
7,V008,2026-08-08,P008,Cadeira Ergonômica,Móveis,2,1299.9,0.10,Lages,Serra,Carla Mendes,Representante,Boleto,Pessoa Jurídica,2599.8,259.980,2339.820
8,V009,2026-08-09,P003,Mouse Sem Fio,Periféricos,10,119.9,0.05,Jaraguá do Sul,Norte,Diego Martins,Online,PIX,Pessoa Física,1199.0,59.950,1139.050
9,V010,2026-08-10,P002,Monitor 24,Informática,2,899.9,0.00,Balneário Camboriú,Vale do Itajaí,Eduarda Alves,Loja Física,Cartão de Crédito,Pessoa Física,1799.8,0.000,1799.800
10,V011,2026-08-11,P001,Notebook Pro 15,Informática,1,3899.9,0.07,Joinville,Norte,Ana Souza,Representante,Boleto,Pessoa Jurídica,3899.9,272.993,3626.907
11,V012,2026-08-12,P004,Teclado Mecânico,Periféricos,7,289.9,0.05,Florianópolis,Grande Florianópolis,Bruno Lima,Online,PIX,Pessoa Física,2029.3,101.465,1927.835
12,V013,2026-08-13,P006,Webcam Full HD,Periféricos,3,249.9,0.00,Blumenau,Vale do Itajaí,Carla Mendes,Loja Física,Cartão de Débito,Pessoa Física,749.7,0.000,749.700
13,V014,2026-08-14,P007,SSD 1TB,Informática,5,459.9,0.12,Chapecó,Oeste,Diego Martins,Representante,Boleto,Pessoa Jurídica,2299.5,275.940,2023.560
14,V015,2026-08-15,P005,Headset USB,Periféricos,9,179.9,0.05,Criciúma,Sul,Eduarda Alves,Online,PIX,Pessoa Física,1619.1,80.955,1538.145
15,V016,2026-08-16,P008,Cadeira Ergonômica,Móveis,3,1299.9,0.08,Itajaí,Vale do Itajaí,Ana Souza,Loja Física,Cartão de Crédito,Pessoa Jurídica,3899.7,311.976,3587.724
16,V017,2026-08-17,P002,Monitor 24,Informática,4,899.9,0.10,São José,Grande Florianópolis,Bruno Lima,Online,Cartão de Crédito,Pessoa Física,3599.6,359.960,3239.640
17,V018,2026-08-18,P003,Mouse Sem Fio,Periféricos,12,119.9,0.00,Lages,Serra,Carla Mendes,Representante,Boleto,Pessoa Jurídica,1438.8,0.000,1438.800
18,V019,2026-08-19,P001,Notebook Pro 15,Informática,2,3899.9,0.05,Jaraguá do Sul,Norte,Diego Martins,Online,PIX,Pessoa Física,7799.8,389.990,7409.810
19,V020,2026-08-20,P006,Webcam Full HD,Periféricos,5,249.9,0.10,Balneário Camboriú,Vale do Itajaí,Eduarda Alves,Loja Física,Cartão de Débito,Pessoa Física,1249.5,124.950,1124.550

In [23]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_venda         20 non-null     object
 1   data_venda       20 non-null     datetime64[ns]
 2   id_produto       20 non-null     object
 3   produto          20 non-null     object
 4   categoria        20 non-null     object
 5   quantidade       20 non-null     int64
 6   preco_unitario   20 non-null     float64
 7   desconto_pct     20 non-null     float64
 8   municipio        20 non-null     object
 9   regiao_sc        20 non-null     object
 10  vendedor         20 non-null     object
 11  canal_venda      20 non-null     object
 12  forma_pagamento  20 non-null     object
 13  tipo_cliente     20 non-null     object
 14  valor_bruto      20 non-null     float64
 15  valor_desconto   20 non-null     float64
 16  valor_liquido    20 non-null     float64
dtypes: datetime64[ns](1), float64(5), int64(1), object(10)
memory usage: 2.8+ KB

In [24]:
#head() — primeiras linhas

df_vendas.head()

,id_venda,data_venda,id_produto,produto,categoria,quantidade,preco_unitario,desconto_pct,municipio,regiao_sc,vendedor,canal_venda,forma_pagamento,tipo_cliente,valor_bruto,valor_desconto,valor_liquido
0,V001,2026-08-01,P001,Notebook Pro 15,Informática,2,3899.9,0.05,Florianópolis,Grande Florianópolis,Ana Souza,Loja Física,Cartão de Crédito,Pessoa Física,7799.8,389.990,7409.810
1,V002,2026-08-02,P003,Mouse Sem Fio,Periféricos,8,119.9,0.00,Joinville,Norte,Bruno Lima,Online,PIX,Pessoa Física,959.2,0.000,959.200
2,V003,2026-08-03,P004,Teclado Mecânico,Periféricos,4,289.9,0.10,Blumenau,Vale do Itajaí,Carla Mendes,Loja Física,Cartão de Crédito,Pessoa Jurídica,1159.6,115.960,1043.640
3,V004,2026-08-04,P002,Monitor 24,Informática,3,899.9,0.05,Chapecó,Oeste,Diego Martins,Representante,Boleto,Pessoa Jurídica,2699.7,134.985,2564.715
4,V005,2026-08-05,P005,Headset USB,Periféricos,5,179.9,0.00,Criciúma,Sul,Eduarda Alves,Online,PIX,Pessoa Física,899.5,0.000,899.500

In [25]:
# tail() — últimas linhas

df_vendas.tail()

,id_venda,data_venda,id_produto,produto,categoria,quantidade,preco_unitario,desconto_pct,municipio,regiao_sc,vendedor,canal_venda,forma_pagamento,tipo_cliente,valor_bruto,valor_desconto,valor_liquido
15,V016,2026-08-16,P008,Cadeira Ergonômica,Móveis,3,1299.9,0.08,Itajaí,Vale do Itajaí,Ana Souza,Loja Física,Cartão de Crédito,Pessoa Jurídica,3899.7,311.976,3587.724
16,V017,2026-08-17,P002,Monitor 24,Informática,4,899.9,0.10,São José,Grande Florianópolis,Bruno Lima,Online,Cartão de Crédito,Pessoa Física,3599.6,359.960,3239.640
17,V018,2026-08-18,P003,Mouse Sem Fio,Periféricos,12,119.9,0.00,Lages,Serra,Carla Mendes,Representante,Boleto,Pessoa Jurídica,1438.8,0.000,1438.800
18,V019,2026-08-19,P001,Notebook Pro 15,Informática,2,3899.9,0.05,Jaraguá do Sul,Norte,Diego Martins,Online,PIX,Pessoa Física,7799.8,389.990,7409.810
19,V020,2026-08-20,P006,Webcam Full HD,Periféricos,5,249.9,0.10,Balneário Camboriú,Vale do Itajaí,Eduarda Alves,Loja Física,Cartão de Débito,Pessoa Física,1249.5,124.950,1124.550

In [26]:
# sample() — linhas aleatórias

df_vendas.sample(5)

,id_venda,data_venda,id_produto,produto,categoria,quantidade,preco_unitario,desconto_pct,municipio,regiao_sc,vendedor,canal_venda,forma_pagamento,tipo_cliente,valor_bruto,valor_desconto,valor_liquido
17,V018,2026-08-18,P003,Mouse Sem Fio,Periféricos,12,119.9,0.00,Lages,Serra,Carla Mendes,Representante,Boleto,Pessoa Jurídica,1438.8,0.000,1438.800
13,V014,2026-08-14,P007,SSD 1TB,Informática,5,459.9,0.12,Chapecó,Oeste,Diego Martins,Representante,Boleto,Pessoa Jurídica,2299.5,275.940,2023.560
7,V008,2026-08-08,P008,Cadeira Ergonômica,Móveis,2,1299.9,0.10,Lages,Serra,Carla Mendes,Representante,Boleto,Pessoa Jurídica,2599.8,259.980,2339.820
16,V017,2026-08-17,P002,Monitor 24,Informática,4,899.9,0.10,São José,Grande Florianópolis,Bruno Lima,Online,Cartão de Crédito,Pessoa Física,3599.6,359.960,3239.640
14,V015,2026-08-15,P005,Headset USB,Periféricos,9,179.9,0.05,Criciúma,Sul,Eduarda Alves,Online,PIX,Pessoa Física,1619.1,80.955,1538.145

In [27]:
# Quantas linhas e colunas temos?

df_vendas.shape

(20, 17)

In [28]:
# nomes das colunas

df_vendas.columns

for i in df_vendas.columns:
    print(i)

id_venda
data_venda
id_produto
produto
categoria
quantidade
preco_unitario
desconto_pct
municipio
regiao_sc
vendedor
canal_venda
forma_pagamento
tipo_cliente
valor_bruto
valor_desconto
valor_liquido

### Filtros e Seleções

In [29]:
# visualizar uma ou mais colunas

df_vendas[['produto', 'quantidade']]

               produto  quantidade
0      Notebook Pro 15           2
1        Mouse Sem Fio           8
2     Teclado Mecânico           4
3           Monitor 24           3
4          Headset USB           5
5       Webcam Full HD           6
6              SSD 1TB           4
7   Cadeira Ergonômica           2
8        Mouse Sem Fio          10
9           Monitor 24           2
10     Notebook Pro 15           1
11    Teclado Mecânico           7
12      Webcam Full HD           3
13             SSD 1TB           5
14         Headset USB           9
15  Cadeira Ergonômica           3
16          Monitor 24           4
17       Mouse Sem Fio          12
18     Notebook Pro 15           2
19      Webcam Full HD           5

#### iloc

In [30]:
# 5 primeiras linhas e 5 primeiras colunas

df_vendas.iloc[0:5, 0:4]

  id_venda data_venda id_produto           produto
0     V001 2026-08-01       P001   Notebook Pro 15
1     V002 2026-08-02       P003     Mouse Sem Fio
2     V003 2026-08-03       P004  Teclado Mecânico
3     V004 2026-08-04       P002        Monitor 24
4     V005 2026-08-05       P005       Headset USB

In [31]:
# todas as linhas e colunas da 4 a 0
df_vendas.iloc[: , 4:9]

      categoria  quantidade  preco_unitario  desconto_pct           municipio
0   Informática           2          3899.9          0.05       Florianópolis
1   Periféricos           8           119.9          0.00           Joinville
2   Periféricos           4           289.9          0.10            Blumenau
3   Informática           3           899.9          0.05             Chapecó
4   Periféricos           5           179.9          0.00            Criciúma
5   Periféricos           6           249.9          0.08              Itajaí
6   Informática           4           459.9          0.03            São José
7        Móveis           2          1299.9          0.10               Lages
8   Periféricos          10           119.9          0.05      Jaraguá do Sul
9   Informática           2           899.9          0.00  Balneário Camboriú
10  Informática           1          3899.9          0.07           Joinville
11  Periféricos           7           289.9          0.05       Florianópolis
12  Periféricos           3           249.9          0.00            Blumenau
13  Informática           5           459.9          0.12             Chapecó
14  Periféricos           9           179.9          0.05            Criciúma
15       Móveis           3          1299.9          0.08              Itajaí
16  Informática           4           899.9          0.10            São José
17  Periféricos          12           119.9          0.00               Lages
18  Informática           2          3899.9          0.05      Jaraguá do Sul
19  Periféricos           5           249.9          0.10  Balneário Camboriú

In [32]:
# até a terceira linha e todas as colunas
df_vendas.iloc[0:3 , :]

,id_venda,data_venda,id_produto,produto,categoria,quantidade,preco_unitario,desconto_pct,municipio,regiao_sc,vendedor,canal_venda,forma_pagamento,tipo_cliente,valor_bruto,valor_desconto,valor_liquido
0,V001,2026-08-01,P001,Notebook Pro 15,Informática,2,3899.9,0.05,Florianópolis,Grande Florianópolis,Ana Souza,Loja Física,Cartão de Crédito,Pessoa Física,7799.8,389.99,7409.81
1,V002,2026-08-02,P003,Mouse Sem Fio,Periféricos,8,119.9,0.00,Joinville,Norte,Bruno Lima,Online,PIX,Pessoa Física,959.2,0.00,959.20
2,V003,2026-08-03,P004,Teclado Mecânico,Periféricos,4,289.9,0.10,Blumenau,Vale do Itajaí,Carla Mendes,Loja Física,Cartão de Crédito,Pessoa Jurídica,1159.6,115.96,1043.64

In [33]:
# média de uma coluna

df_vendas["quantidade"].mean()

np.float64(4.85)

In [34]:
# criar colunas

df_vendas['preco_unitario_10%'] = df_vendas["preco_unitario"] * 1.1

df_vendas

,id_venda,data_venda,id_produto,produto,categoria,quantidade,preco_unitario,desconto_pct,municipio,regiao_sc,vendedor,canal_venda,forma_pagamento,tipo_cliente,valor_bruto,valor_desconto,valor_liquido,preco_unitario_10%
0,V001,2026-08-01,P001,Notebook Pro 15,Informática,2,3899.9,0.05,Florianópolis,Grande Florianópolis,Ana Souza,Loja Física,Cartão de Crédito,Pessoa Física,7799.8,389.990,7409.810,4289.89
1,V002,2026-08-02,P003,Mouse Sem Fio,Periféricos,8,119.9,0.00,Joinville,Norte,Bruno Lima,Online,PIX,Pessoa Física,959.2,0.000,959.200,131.89
2,V003,2026-08-03,P004,Teclado Mecânico,Periféricos,4,289.9,0.10,Blumenau,Vale do Itajaí,Carla Mendes,Loja Física,Cartão de Crédito,Pessoa Jurídica,1159.6,115.960,1043.640,318.89
3,V004,2026-08-04,P002,Monitor 24,Informática,3,899.9,0.05,Chapecó,Oeste,Diego Martins,Representante,Boleto,Pessoa Jurídica,2699.7,134.985,2564.715,989.89
4,V005,2026-08-05,P005,Headset USB,Periféricos,5,179.9,0.00,Criciúma,Sul,Eduarda Alves,Online,PIX,Pessoa Física,899.5,0.000,899.500,197.89
5,V006,2026-08-06,P006,Webcam Full HD,Periféricos,6,249.9,0.08,Itajaí,Vale do Itajaí,Ana Souza,Online,Cartão de Crédito,Pessoa Jurídica,1499.4,119.952,1379.448,274.89
6,V007,2026-08-07,P007,SSD 1TB,Informática,4,459.9,0.03,São José,Grande Florianópolis,Bruno Lima,Loja Física,PIX,Pessoa Física,1839.6,55.188,1784.412,505.89
7,V008,2026-08-08,P008,Cadeira Ergonômica,Móveis,2,1299.9,0.10,Lages,Serra,Carla Mendes,Representante,Boleto,Pessoa Jurídica,2599.8,259.980,2339.820,1429.89
8,V009,2026-08-09,P003,Mouse Sem Fio,Periféricos,10,119.9,0.05,Jaraguá do Sul,Norte,Diego Martins,Online,PIX,Pessoa Física,1199.0,59.950,1139.050,131.89
9,V010,2026-08-10,P002,Monitor 24,Informática,2,899.9,0.00,Balneário Camboriú,Vale do Itajaí,Eduarda Alves,Loja Física,Cartão de Crédito,Pessoa Física,1799.8,0.000,1799.800,989.89
10,V011,2026-08-11,P001,Notebook Pro 15,Informática,1,3899.9,0.07,Joinville,Norte,Ana Souza,Representante,Boleto,Pessoa Jurídica,3899.9,272.993,3626.907,4289.89
11,V012,2026-08-12,P004,Teclado Mecânico,Periféricos,7,289.9,0.05,Florianópolis,Grande Florianópolis,Bruno Lima,Online,PIX,Pessoa Física,2029.3,101.465,1927.835,318.89
12,V013,2026-08-13,P006,Webcam Full HD,Periféricos,3,249.9,0.00,Blumenau,Vale do Itajaí,Carla Mendes,Loja Física,Cartão de Débito,Pessoa Física,749.7,0.000,749.700,274.89
13,V014,2026-08-14,P007,SSD 1TB,Informática,5,459.9,0.12,Chapecó,Oeste,Diego Martins,Representante,Boleto,Pessoa Jurídica,2299.5,275.940,2023.560,505.89
14,V015,2026-08-15,P005,Headset USB,Periféricos,9,179.9,0.05,Criciúma,Sul,Eduarda Alves,Online,PIX,Pessoa Física,1619.1,80.955,1538.145,197.89
15,V016,2026-08-16,P008,Cadeira Ergonômica,Móveis,3,1299.9,0.08,Itajaí,Vale do Itajaí,Ana Souza,Loja Física,Cartão de Crédito,Pessoa Jurídica,3899.7,311.976,3587.724,1429.89
16,V017,2026-08-17,P002,Monitor 24,Informática,4,899.9,0.10,São José,Grande Florianópolis,Bruno Lima,Online,Cartão de Crédito,Pessoa Física,3599.6,359.960,3239.640,989.89
17,V018,2026-08-18,P003,Mouse Sem Fio,Periféricos,12,119.9,0.00,Lages,Serra,Carla Mendes,Representante,Boleto,Pessoa Jurídica,1438.8,0.000,1438.800,131.89
18,V019,2026-08-19,P001,Notebook Pro 15,Informática,2,3899.9,0.05,Jaraguá do Sul,Norte,Diego Martins,Online,PIX,Pessoa Física,7799.8,389.990,7409.810,4289.89
19,V020,2026-08-20,P006,Webcam Full HD,Periféricos,5,249.9,0.10,Balneário Camboriú,Vale do Itajaí,Eduarda Alves,Loja Física,Cartão de Débito,Pessoa Física,1249.5,124.950,1124.550,274.89

In [35]:
# visualizar somente as vendas realizadas em Joinville.

display(df_vendas["municipio"] == "Joinville")

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: municipio, dtype: bool

In [36]:
display(df_vendas[df_vendas["municipio"] == "Joinville"])

,id_venda,data_venda,id_produto,produto,categoria,quantidade,preco_unitario,desconto_pct,municipio,regiao_sc,vendedor,canal_venda,forma_pagamento,tipo_cliente,valor_bruto,valor_desconto,valor_liquido,preco_unitario_10%
1,V002,2026-08-02,P003,Mouse Sem Fio,Periféricos,8,119.9,0.00,Joinville,Norte,Bruno Lima,Online,PIX,Pessoa Física,959.2,0.000,959.200,131.89
10,V011,2026-08-11,P001,Notebook Pro 15,Informática,1,3899.9,0.07,Joinville,Norte,Ana Souza,Representante,Boleto,Pessoa Jurídica,3899.9,272.993,3626.907,4289.89

In [37]:
df_vendas[df_vendas["quantidade"] > 5]

,id_venda,data_venda,id_produto,produto,categoria,quantidade,preco_unitario,desconto_pct,municipio,regiao_sc,vendedor,canal_venda,forma_pagamento,tipo_cliente,valor_bruto,valor_desconto,valor_liquido,preco_unitario_10%
1,V002,2026-08-02,P003,Mouse Sem Fio,Periféricos,8,119.9,0.00,Joinville,Norte,Bruno Lima,Online,PIX,Pessoa Física,959.2,0.000,959.200,131.89
5,V006,2026-08-06,P006,Webcam Full HD,Periféricos,6,249.9,0.08,Itajaí,Vale do Itajaí,Ana Souza,Online,Cartão de Crédito,Pessoa Jurídica,1499.4,119.952,1379.448,274.89
8,V009,2026-08-09,P003,Mouse Sem Fio,Periféricos,10,119.9,0.05,Jaraguá do Sul,Norte,Diego Martins,Online,PIX,Pessoa Física,1199.0,59.950,1139.050,131.89
11,V012,2026-08-12,P004,Teclado Mecânico,Periféricos,7,289.9,0.05,Florianópolis,Grande Florianópolis,Bruno Lima,Online,PIX,Pessoa Física,2029.3,101.465,1927.835,318.89
14,V015,2026-08-15,P005,Headset USB,Periféricos,9,179.9,0.05,Criciúma,Sul,Eduarda Alves,Online,PIX,Pessoa Física,1619.1,80.955,1538.145,197.89
17,V018,2026-08-18,P003,Mouse Sem Fio,Periféricos,12,119.9,0.00,Lages,Serra,Carla Mendes,Representante,Boleto,Pessoa Jurídica,1438.8,0.000,1438.800,131.89

In [38]:
df_vendas[df_vendas["categoria"] == "Informática"]

,id_venda,data_venda,id_produto,produto,categoria,quantidade,preco_unitario,desconto_pct,municipio,regiao_sc,vendedor,canal_venda,forma_pagamento,tipo_cliente,valor_bruto,valor_desconto,valor_liquido,preco_unitario_10%
0,V001,2026-08-01,P001,Notebook Pro 15,Informática,2,3899.9,0.05,Florianópolis,Grande Florianópolis,Ana Souza,Loja Física,Cartão de Crédito,Pessoa Física,7799.8,389.990,7409.810,4289.89
3,V004,2026-08-04,P002,Monitor 24,Informática,3,899.9,0.05,Chapecó,Oeste,Diego Martins,Representante,Boleto,Pessoa Jurídica,2699.7,134.985,2564.715,989.89
6,V007,2026-08-07,P007,SSD 1TB,Informática,4,459.9,0.03,São José,Grande Florianópolis,Bruno Lima,Loja Física,PIX,Pessoa Física,1839.6,55.188,1784.412,505.89
9,V010,2026-08-10,P002,Monitor 24,Informática,2,899.9,0.00,Balneário Camboriú,Vale do Itajaí,Eduarda Alves,Loja Física,Cartão de Crédito,Pessoa Física,1799.8,0.000,1799.800,989.89
10,V011,2026-08-11,P001,Notebook Pro 15,Informática,1,3899.9,0.07,Joinville,Norte,Ana Souza,Representante,Boleto,Pessoa Jurídica,3899.9,272.993,3626.907,4289.89
13,V014,2026-08-14,P007,SSD 1TB,Informática,5,459.9,0.12,Chapecó,Oeste,Diego Martins,Representante,Boleto,Pessoa Jurídica,2299.5,275.940,2023.560,505.89
16,V017,2026-08-17,P002,Monitor 24,Informática,4,899.9,0.10,São José,Grande Florianópolis,Bruno Lima,Online,Cartão de Crédito,Pessoa Física,3599.6,359.960,3239.640,989.89
18,V019,2026-08-19,P001,Notebook Pro 15,Informática,2,3899.9,0.05,Jaraguá do Sul,Norte,Diego Martins,Online,PIX,Pessoa Física,7799.8,389.990,7409.810,4289.89

In [39]:
df_vendas[df_vendas["canal_venda"] != "Online"]

,id_venda,data_venda,id_produto,produto,categoria,quantidade,preco_unitario,desconto_pct,municipio,regiao_sc,vendedor,canal_venda,forma_pagamento,tipo_cliente,valor_bruto,valor_desconto,valor_liquido,preco_unitario_10%
0,V001,2026-08-01,P001,Notebook Pro 15,Informática,2,3899.9,0.05,Florianópolis,Grande Florianópolis,Ana Souza,Loja Física,Cartão de Crédito,Pessoa Física,7799.8,389.990,7409.810,4289.89
2,V003,2026-08-03,P004,Teclado Mecânico,Periféricos,4,289.9,0.10,Blumenau,Vale do Itajaí,Carla Mendes,Loja Física,Cartão de Crédito,Pessoa Jurídica,1159.6,115.960,1043.640,318.89
3,V004,2026-08-04,P002,Monitor 24,Informática,3,899.9,0.05,Chapecó,Oeste,Diego Martins,Representante,Boleto,Pessoa Jurídica,2699.7,134.985,2564.715,989.89
6,V007,2026-08-07,P007,SSD 1TB,Informática,4,459.9,0.03,São José,Grande Florianópolis,Bruno Lima,Loja Física,PIX,Pessoa Física,1839.6,55.188,1784.412,505.89
7,V008,2026-08-08,P008,Cadeira Ergonômica,Móveis,2,1299.9,0.10,Lages,Serra,Carla Mendes,Representante,Boleto,Pessoa Jurídica,2599.8,259.980,2339.820,1429.89
9,V010,2026-08-10,P002,Monitor 24,Informática,2,899.9,0.00,Balneário Camboriú,Vale do Itajaí,Eduarda Alves,Loja Física,Cartão de Crédito,Pessoa Física,1799.8,0.000,1799.800,989.89
10,V011,2026-08-11,P001,Notebook Pro 15,Informática,1,3899.9,0.07,Joinville,Norte,Ana Souza,Representante,Boleto,Pessoa Jurídica,3899.9,272.993,3626.907,4289.89
12,V013,2026-08-13,P006,Webcam Full HD,Periféricos,3,249.9,0.00,Blumenau,Vale do Itajaí,Carla Mendes,Loja Física,Cartão de Débito,Pessoa Física,749.7,0.000,749.700,274.89
13,V014,2026-08-14,P007,SSD 1TB,Informática,5,459.9,0.12,Chapecó,Oeste,Diego Martins,Representante,Boleto,Pessoa Jurídica,2299.5,275.940,2023.560,505.89
15,V016,2026-08-16,P008,Cadeira Ergonômica,Móveis,3,1299.9,0.08,Itajaí,Vale do Itajaí,Ana Souza,Loja Física,Cartão de Crédito,Pessoa Jurídica,3899.7,311.976,3587.724,1429.89
17,V018,2026-08-18,P003,Mouse Sem Fio,Periféricos,12,119.9,0.00,Lages,Serra,Carla Mendes,Representante,Boleto,Pessoa Jurídica,1438.8,0.000,1438.800,131.89
19,V020,2026-08-20,P006,Webcam Full HD,Periféricos,5,249.9,0.10,Balneário Camboriú,Vale do Itajaí,Eduarda Alves,Loja Física,Cartão de Débito,Pessoa Física,1249.5,124.950,1124.550,274.89

In [40]:
# Guardando o resultado

#df_vendas_joinville = df_vendas[df_vendas["municipio"] == "Joinville"]


df_vendas_joinville =  df_vendas[df_vendas["municipio"] == "Blumenau"].copy()

df_vendas_joinville

,id_venda,data_venda,id_produto,produto,categoria,quantidade,preco_unitario,desconto_pct,municipio,regiao_sc,vendedor,canal_venda,forma_pagamento,tipo_cliente,valor_bruto,valor_desconto,valor_liquido,preco_unitario_10%
2,V003,2026-08-03,P004,Teclado Mecânico,Periféricos,4,289.9,0.1,Blumenau,Vale do Itajaí,Carla Mendes,Loja Física,Cartão de Crédito,Pessoa Jurídica,1159.6,115.96,1043.64,318.89
12,V013,2026-08-13,P006,Webcam Full HD,Periféricos,3,249.9,0.0,Blumenau,Vale do Itajaí,Carla Mendes,Loja Física,Cartão de Débito,Pessoa Física,749.7,0.00,749.70,274.89

In [41]:
# Duas condições — operador &

# Cada comparação precisa ficar entre parênteses antes de utilizarmos:

df_vendas[(df_vendas["categoria"] == "Informática")  & (df_vendas["municipio"] == "Florianópolis")]

,id_venda,data_venda,id_produto,produto,categoria,quantidade,preco_unitario,desconto_pct,municipio,regiao_sc,vendedor,canal_venda,forma_pagamento,tipo_cliente,valor_bruto,valor_desconto,valor_liquido,preco_unitario_10%
0,V001,2026-08-01,P001,Notebook Pro 15,Informática,2,3899.9,0.05,Florianópolis,Grande Florianópolis,Ana Souza,Loja Física,Cartão de Crédito,Pessoa Física,7799.8,389.99,7409.81,4289.89

In [42]:
# Duas condições — operador |

df_vendas[(df_vendas["municipio"] == "Joinville") | (df_vendas["municipio"] == "Blumenau")]

,id_venda,data_venda,id_produto,produto,categoria,quantidade,preco_unitario,desconto_pct,municipio,regiao_sc,vendedor,canal_venda,forma_pagamento,tipo_cliente,valor_bruto,valor_desconto,valor_liquido,preco_unitario_10%
1,V002,2026-08-02,P003,Mouse Sem Fio,Periféricos,8,119.9,0.00,Joinville,Norte,Bruno Lima,Online,PIX,Pessoa Física,959.2,0.000,959.200,131.89
2,V003,2026-08-03,P004,Teclado Mecânico,Periféricos,4,289.9,0.10,Blumenau,Vale do Itajaí,Carla Mendes,Loja Física,Cartão de Crédito,Pessoa Jurídica,1159.6,115.960,1043.640,318.89
10,V011,2026-08-11,P001,Notebook Pro 15,Informática,1,3899.9,0.07,Joinville,Norte,Ana Souza,Representante,Boleto,Pessoa Jurídica,3899.9,272.993,3626.907,4289.89
12,V013,2026-08-13,P006,Webcam Full HD,Periféricos,3,249.9,0.00,Blumenau,Vale do Itajaí,Carla Mendes,Loja Física,Cartão de Débito,Pessoa Física,749.7,0.000,749.700,274.89

In [43]:
df_vendas[(df_vendas["categoria"] == "Periféricos") & (df_vendas["quantidade"] > 5)]

,id_venda,data_venda,id_produto,produto,categoria,quantidade,preco_unitario,desconto_pct,municipio,regiao_sc,vendedor,canal_venda,forma_pagamento,tipo_cliente,valor_bruto,valor_desconto,valor_liquido,preco_unitario_10%
1,V002,2026-08-02,P003,Mouse Sem Fio,Periféricos,8,119.9,0.00,Joinville,Norte,Bruno Lima,Online,PIX,Pessoa Física,959.2,0.000,959.200,131.89
5,V006,2026-08-06,P006,Webcam Full HD,Periféricos,6,249.9,0.08,Itajaí,Vale do Itajaí,Ana Souza,Online,Cartão de Crédito,Pessoa Jurídica,1499.4,119.952,1379.448,274.89
8,V009,2026-08-09,P003,Mouse Sem Fio,Periféricos,10,119.9,0.05,Jaraguá do Sul,Norte,Diego Martins,Online,PIX,Pessoa Física,1199.0,59.950,1139.050,131.89
11,V012,2026-08-12,P004,Teclado Mecânico,Periféricos,7,289.9,0.05,Florianópolis,Grande Florianópolis,Bruno Lima,Online,PIX,Pessoa Física,2029.3,101.465,1927.835,318.89
14,V015,2026-08-15,P005,Headset USB,Periféricos,9,179.9,0.05,Criciúma,Sul,Eduarda Alves,Online,PIX,Pessoa Física,1619.1,80.955,1538.145,197.89
17,V018,2026-08-18,P003,Mouse Sem Fio,Periféricos,12,119.9,0.00,Lages,Serra,Carla Mendes,Representante,Boleto,Pessoa Jurídica,1438.8,0.000,1438.800,131.89

In [44]:
# isin() — uma maneira melhor de trabalhar com vários valores

df_vendas[df_vendas["municipio"].isin(["Joinville", "Blumenau", "Florianópolis"])]

,id_venda,data_venda,id_produto,produto,categoria,quantidade,preco_unitario,desconto_pct,municipio,regiao_sc,vendedor,canal_venda,forma_pagamento,tipo_cliente,valor_bruto,valor_desconto,valor_liquido,preco_unitario_10%
0,V001,2026-08-01,P001,Notebook Pro 15,Informática,2,3899.9,0.05,Florianópolis,Grande Florianópolis,Ana Souza,Loja Física,Cartão de Crédito,Pessoa Física,7799.8,389.990,7409.810,4289.89
1,V002,2026-08-02,P003,Mouse Sem Fio,Periféricos,8,119.9,0.00,Joinville,Norte,Bruno Lima,Online,PIX,Pessoa Física,959.2,0.000,959.200,131.89
2,V003,2026-08-03,P004,Teclado Mecânico,Periféricos,4,289.9,0.10,Blumenau,Vale do Itajaí,Carla Mendes,Loja Física,Cartão de Crédito,Pessoa Jurídica,1159.6,115.960,1043.640,318.89
10,V011,2026-08-11,P001,Notebook Pro 15,Informática,1,3899.9,0.07,Joinville,Norte,Ana Souza,Representante,Boleto,Pessoa Jurídica,3899.9,272.993,3626.907,4289.89
11,V012,2026-08-12,P004,Teclado Mecânico,Periféricos,7,289.9,0.05,Florianópolis,Grande Florianópolis,Bruno Lima,Online,PIX,Pessoa Física,2029.3,101.465,1927.835,318.89
12,V013,2026-08-13,P006,Webcam Full HD,Periféricos,3,249.9,0.00,Blumenau,Vale do Itajaí,Carla Mendes,Loja Física,Cartão de Débito,Pessoa Física,749.7,0.000,749.700,274.89

### groupby, merge e pivot

#### groupby() — agrupando dados

In [45]:
# Quanto foi vendido em cada município?

df_vendas.groupby("municipio")["valor_liquido"].sum()

# .sum()
# .mean()
# .min()
# .max()
# .count()

municipio
Balneário Camboriú    2924.350
Blumenau              1793.340
Chapecó               4588.275
Criciúma              2437.645
Florianópolis         9337.645
Itajaí                4967.172
Jaraguá do Sul        8548.860
Joinville             4586.107
Lages                 3778.620
São José              5024.052
Name: valor_liquido, dtype: float64

In [46]:
# Quantas unidades de cada produto foram vendidas?

df_vendas.groupby("produto")["quantidade"].sum()

produto
Cadeira Ergonômica     5
Headset USB           14
Monitor 24             9
Mouse Sem Fio         30
Notebook Pro 15        5
SSD 1TB                9
Teclado Mecânico      11
Webcam Full HD        14
Name: quantidade, dtype: int64

In [47]:
df_faturamento_municipio = (df_vendas.groupby("municipio")["valor_liquido"].sum()
                            .reset_index()
                            .sort_values("valor_liquido", ascending = False))

df_faturamento_municipio

            municipio  valor_liquido
4       Florianópolis       9337.645
6      Jaraguá do Sul       8548.860
9            São José       5024.052
5              Itajaí       4967.172
2             Chapecó       4588.275
7           Joinville       4586.107
8               Lages       3778.620
0  Balneário Camboriú       2924.350
3            Criciúma       2437.645
1            Blumenau       1793.340

In [48]:
# Agrupando por duas colunas

df_vendas.groupby(["municipio", "categoria"])["valor_liquido"].sum().reset_index()

             municipio    categoria  valor_liquido
0   Balneário Camboriú  Informática       1799.800
1   Balneário Camboriú  Periféricos       1124.550
2             Blumenau  Periféricos       1793.340
3              Chapecó  Informática       4588.275
4             Criciúma  Periféricos       2437.645
5        Florianópolis  Informática       7409.810
6        Florianópolis  Periféricos       1927.835
7               Itajaí       Móveis       3587.724
8               Itajaí  Periféricos       1379.448
9       Jaraguá do Sul  Informática       7409.810
10      Jaraguá do Sul  Periféricos       1139.050
11           Joinville  Informática       3626.907
12           Joinville  Periféricos        959.200
13               Lages       Móveis       2339.820
14               Lages  Periféricos       1438.800
15            São José  Informática       5024.052

In [49]:
# várias métricas ao mesmo tempo

df_resumo = (
    df_vendas
    .groupby("municipio").agg(
        faturamento=("valor_liquido", "sum"),
        quantidade_vendida=("quantidade", "sum"),
        venda_media=("valor_liquido", "mean"),
        numero_vendas=("id_venda", "count")
    ).reset_index()
)

df_resumo

,municipio,faturamento,quantidade_vendida,venda_media,numero_vendas
0,Balneário Camboriú,2924.350,7,1462.1750,2
1,Blumenau,1793.340,7,896.6700,2
2,Chapecó,4588.275,8,2294.1375,2
3,Criciúma,2437.645,14,1218.8225,2
4,Florianópolis,9337.645,9,4668.8225,2
5,Itajaí,4967.172,9,2483.5860,2
6,Jaraguá do Sul,8548.860,12,4274.4300,2
7,Joinville,4586.107,9,2293.0535,2
8,Lages,3778.620,14,1889.3100,2
9,São José,5024.052,8,2512.0260,2

### merge() — relacionando duas ou mais tabelas

In [50]:
df_produtos = pd.read_excel("perfil_produtos.xlsx")

df_produtos

  id_produto  fornecedor  custo_unitario  estoque_atual  garantia_meses
0       P001     TechSul            2900             15              24
1       P002  VisionTech             620             24              12
2       P003  Connect SC              65             70              12
3       P004  Connect SC             180             42              12
4       P005    AudioMax             105             38              12
5       P006  VisionTech             160             31              12
6       P007  StorageSul             300             26              24
7       P008   OfficeSul             850             12              12

In [51]:
df_vendas_completo = pd.merge(df_vendas, df_produtos, on="id_produto")

df_vendas_completo

,id_venda,data_venda,id_produto,produto,categoria,quantidade,preco_unitario,desconto_pct,municipio,regiao_sc,...,forma_pagamento,tipo_cliente,valor_bruto,valor_desconto,valor_liquido,preco_unitario_10%,fornecedor,custo_unitario,estoque_atual,garantia_meses
0,V001,2026-08-01,P001,Notebook Pro 15,Informática,2,3899.9,0.05,Florianópolis,Grande Florianópolis,...,Cartão de Crédito,Pessoa Física,7799.8,389.990,7409.810,4289.89,TechSul,2900,15,24
1,V002,2026-08-02,P003,Mouse Sem Fio,Periféricos,8,119.9,0.00,Joinville,Norte,...,PIX,Pessoa Física,959.2,0.000,959.200,131.89,Connect SC,65,70,12
2,V003,2026-08-03,P004,Teclado Mecânico,Periféricos,4,289.9,0.10,Blumenau,Vale do Itajaí,...,Cartão de Crédito,Pessoa Jurídica,1159.6,115.960,1043.640,318.89,Connect SC,180,42,12
3,V004,2026-08-04,P002,Monitor 24,Informática,3,899.9,0.05,Chapecó,Oeste,...,Boleto,Pessoa Jurídica,2699.7,134.985,2564.715,989.89,VisionTech,620,24,12
4,V005,2026-08-05,P005,Headset USB,Periféricos,5,179.9,0.00,Criciúma,Sul,...,PIX,Pessoa Física,899.5,0.000,899.500,197.89,AudioMax,105,38,12
5,V006,2026-08-06,P006,Webcam Full HD,Periféricos,6,249.9,0.08,Itajaí,Vale do Itajaí,...,Cartão de Crédito,Pessoa Jurídica,1499.4,119.952,1379.448,274.89,VisionTech,160,31,12
6,V007,2026-08-07,P007,SSD 1TB,Informática,4,459.9,0.03,São José,Grande Florianópolis,...,PIX,Pessoa Física,1839.6,55.188,1784.412,505.89,StorageSul,300,26,24
7,V008,2026-08-08,P008,Cadeira Ergonômica,Móveis,2,1299.9,0.10,Lages,Serra,...,Boleto,Pessoa Jurídica,2599.8,259.980,2339.820,1429.89,OfficeSul,850,12,12
8,V009,2026-08-09,P003,Mouse Sem Fio,Periféricos,10,119.9,0.05,Jaraguá do Sul,Norte,...,PIX,Pessoa Física,1199.0,59.950,1139.050,131.89,Connect SC,65,70,12
9,V010,2026-08-10,P002,Monitor 24,Informática,2,899.9,0.00,Balneário Camboriú,Vale do Itajaí,...,Cartão de Crédito,Pessoa Física,1799.8,0.000,1799.800,989.89,VisionTech,620,24,12
10,V011,2026-08-11,P001,Notebook Pro 15,Informática,1,3899.9,0.07,Joinville,Norte,...,Boleto,Pessoa Jurídica,3899.9,272.993,3626.907,4289.89,TechSul,2900,15,24
11,V012,2026-08-12,P004,Teclado Mecânico,Periféricos,7,289.9,0.05,Florianópolis,Grande Florianópolis,...,PIX,Pessoa Física,2029.3,101.465,1927.835,318.89,Connect SC,180,42,12
12,V013,2026-08-13,P006,Webcam Full HD,Periféricos,3,249.9,0.00,Blumenau,Vale do Itajaí,...,Cartão de Débito,Pessoa Física,749.7,0.000,749.700,274.89,VisionTech,160,31,12
13,V014,2026-08-14,P007,SSD 1TB,Informática,5,459.9,0.12,Chapecó,Oeste,...,Boleto,Pessoa Jurídica,2299.5,275.940,2023.560,505.89,StorageSul,300,26,24
14,V015,2026-08-15,P005,Headset USB,Periféricos,9,179.9,0.05,Criciúma,Sul,...,PIX,Pessoa Física,1619.1,80.955,1538.145,197.89,AudioMax,105,38,12
15,V016,2026-08-16,P008,Cadeira Ergonômica,Móveis,3,1299.9,0.08,Itajaí,Vale do Itajaí,...,Cartão de Crédito,Pessoa Jurídica,3899.7,311.976,3587.724,1429.89,OfficeSul,850,12,12
16,V017,2026-08-17,P002,Monitor 24,Informática,4,899.9,0.10,São José,Grande Florianópolis,...,Cartão de Crédito,Pessoa Física,3599.6,359.960,3239.640,989.89,VisionTech,620,24,12
17,V018,2026-08-18,P003,Mouse Sem Fio,Periféricos,12,119.9,0.00,Lages,Serra,...,Boleto,Pessoa Jurídica,1438.8,0.000,1438.800,131.89,Connect SC,65,70,12
18,V019,2026-08-19,P001,Notebook Pro 15,Informática,2,3899.9,0.05,Jaraguá do Sul,Norte,...,PIX,Pessoa Física,7799.8,389.990,7409.810,4289.89,TechSul,2900,15,24
19,V020,2026-08-20,P006,Webcam Full HD,Periféricos,5,249.9,0.10,Balneário Camboriú,Vale do Itajaí,...,Cartão de Débito,Pessoa Física,1249.5,124.950,1124.550,274.89,VisionTech,160,31,12

In [52]:
df_vendas_completo = pd.merge(df_vendas, df_produtos, left_on= "id_produto", right_on= "id_produto", how = "inner")

# inner - Retorna apenas as linhas que possuem chaves correspondentes em ambas as tabelas.
# left - Mantém todas as linhas da tabela da esquerda e adiciona os dados correspondentes da direita (preenche com NaN se não houver par)
# right - Mantém todas as linhas da tabela da direita e adiciona os dados correspondentes da esquerda (preenche com NaN se não houver par).
# outer - Retorna todas as linhas de ambas as tabelas, combinando onde há correspondência e preenchendo com NaN onde não há.

In [53]:
df_fornecedores = pd.read_excel("fornecedores.xlsx")

df_fornecedores

   fornecedor    cidade_sede  prazo_entrega_dias  avaliacao
0     TechSul  Florianópolis                   3        4.8
1  VisionTech      Joinville                   4        4.5
2  Connect SC       Blumenau                   2        4.7
3    AudioMax       Criciúma                   5        4.3
4  StorageSul        Chapecó                   6        4.6
5   OfficeSul       São José                   3        4.4

In [54]:
df_completo = (

    pd.merge(df_vendas, df_produtos, on = "id_produto", how = 'left')
    .merge(df_fornecedores, on = "fornecedor", how = "left"))

df_completo

# how="left" preservam a tabela que está à esquerda de cada merge.

,id_venda,data_venda,id_produto,produto,categoria,quantidade,preco_unitario,desconto_pct,municipio,regiao_sc,...,valor_desconto,valor_liquido,preco_unitario_10%,fornecedor,custo_unitario,estoque_atual,garantia_meses,cidade_sede,prazo_entrega_dias,avaliacao
0,V001,2026-08-01,P001,Notebook Pro 15,Informática,2,3899.9,0.05,Florianópolis,Grande Florianópolis,...,389.990,7409.810,4289.89,TechSul,2900,15,24,Florianópolis,3,4.8
1,V002,2026-08-02,P003,Mouse Sem Fio,Periféricos,8,119.9,0.00,Joinville,Norte,...,0.000,959.200,131.89,Connect SC,65,70,12,Blumenau,2,4.7
2,V003,2026-08-03,P004,Teclado Mecânico,Periféricos,4,289.9,0.10,Blumenau,Vale do Itajaí,...,115.960,1043.640,318.89,Connect SC,180,42,12,Blumenau,2,4.7
3,V004,2026-08-04,P002,Monitor 24,Informática,3,899.9,0.05,Chapecó,Oeste,...,134.985,2564.715,989.89,VisionTech,620,24,12,Joinville,4,4.5
4,V005,2026-08-05,P005,Headset USB,Periféricos,5,179.9,0.00,Criciúma,Sul,...,0.000,899.500,197.89,AudioMax,105,38,12,Criciúma,5,4.3
5,V006,2026-08-06,P006,Webcam Full HD,Periféricos,6,249.9,0.08,Itajaí,Vale do Itajaí,...,119.952,1379.448,274.89,VisionTech,160,31,12,Joinville,4,4.5
6,V007,2026-08-07,P007,SSD 1TB,Informática,4,459.9,0.03,São José,Grande Florianópolis,...,55.188,1784.412,505.89,StorageSul,300,26,24,Chapecó,6,4.6
7,V008,2026-08-08,P008,Cadeira Ergonômica,Móveis,2,1299.9,0.10,Lages,Serra,...,259.980,2339.820,1429.89,OfficeSul,850,12,12,São José,3,4.4
8,V009,2026-08-09,P003,Mouse Sem Fio,Periféricos,10,119.9,0.05,Jaraguá do Sul,Norte,...,59.950,1139.050,131.89,Connect SC,65,70,12,Blumenau,2,4.7
9,V010,2026-08-10,P002,Monitor 24,Informática,2,899.9,0.00,Balneário Camboriú,Vale do Itajaí,...,0.000,1799.800,989.89,VisionTech,620,24,12,Joinville,4,4.5
10,V011,2026-08-11,P001,Notebook Pro 15,Informática,1,3899.9,0.07,Joinville,Norte,...,272.993,3626.907,4289.89,TechSul,2900,15,24,Florianópolis,3,4.8
11,V012,2026-08-12,P004,Teclado Mecânico,Periféricos,7,289.9,0.05,Florianópolis,Grande Florianópolis,...,101.465,1927.835,318.89,Connect SC,180,42,12,Blumenau,2,4.7
12,V013,2026-08-13,P006,Webcam Full HD,Periféricos,3,249.9,0.00,Blumenau,Vale do Itajaí,...,0.000,749.700,274.89,VisionTech,160,31,12,Joinville,4,4.5
13,V014,2026-08-14,P007,SSD 1TB,Informática,5,459.9,0.12,Chapecó,Oeste,...,275.940,2023.560,505.89,StorageSul,300,26,24,Chapecó,6,4.6
14,V015,2026-08-15,P005,Headset USB,Periféricos,9,179.9,0.05,Criciúma,Sul,...,80.955,1538.145,197.89,AudioMax,105,38,12,Criciúma,5,4.3
15,V016,2026-08-16,P008,Cadeira Ergonômica,Móveis,3,1299.9,0.08,Itajaí,Vale do Itajaí,...,311.976,3587.724,1429.89,OfficeSul,850,12,12,São José,3,4.4
16,V017,2026-08-17,P002,Monitor 24,Informática,4,899.9,0.10,São José,Grande Florianópolis,...,359.960,3239.640,989.89,VisionTech,620,24,12,Joinville,4,4.5
17,V018,2026-08-18,P003,Mouse Sem Fio,Periféricos,12,119.9,0.00,Lages,Serra,...,0.000,1438.800,131.89,Connect SC,65,70,12,Blumenau,2,4.7
18,V019,2026-08-19,P001,Notebook Pro 15,Informática,2,3899.9,0.05,Jaraguá do Sul,Norte,...,389.990,7409.810,4289.89,TechSul,2900,15,24,Florianópolis,3,4.8
19,V020,2026-08-20,P006,Webcam Full HD,Periféricos,5,249.9,0.10,Balneário Camboriú,Vale do Itajaí,...,124.950,1124.550,274.89,VisionTech,160,31,12,Joinville,4,4.5

#### pivot_table - cruzar categorias em linhas e colunas

In [55]:
# Faturamento por município e categoria.

df_pivot = pd.pivot_table(
    df_vendas,
    values="valor_liquido", # É o valor que queremos analisar.
    index="municipio", # Serão as linhas.
    columns="categoria", # Serão as colunas.
    aggfunc="sum" # Será a operação realizada.
)

df_pivot

categoria           Informática    Móveis  Periféricos
municipio
Balneário Camboriú     1799.800       NaN     1124.550
Blumenau                    NaN       NaN     1793.340
Chapecó                4588.275       NaN          NaN
Criciúma                    NaN       NaN     2437.645
Florianópolis          7409.810       NaN     1927.835
Itajaí                      NaN  3587.724     1379.448
Jaraguá do Sul         7409.810       NaN     1139.050
Joinville              3626.907       NaN      959.200
Lages                       NaN  2339.820     1438.800
São José               5024.052       NaN          NaN

In [56]:
# Melhorando a tabela com fill_value

df_pivot = pd.pivot_table(
    df_vendas,
    values="valor_liquido",
    index="municipio",
    columns="categoria",
    aggfunc="sum",
    fill_value=0
).reset_index()

df_pivot

categoria           municipio  Informática    Móveis  Periféricos
0          Balneário Camboriú     1799.800     0.000     1124.550
1                    Blumenau        0.000     0.000     1793.340
2                     Chapecó     4588.275     0.000        0.000
3                    Criciúma        0.000     0.000     2437.645
4               Florianópolis     7409.810     0.000     1927.835
5                      Itajaí        0.000  3587.724     1379.448
6              Jaraguá do Sul     7409.810     0.000     1139.050
7                   Joinville     3626.907     0.000      959.200
8                       Lages        0.000  2339.820     1438.800
9                    São José     5024.052     0.000        0.000

In [57]:
# Adicionando totais

df_pivot = pd.pivot_table(
    df_vendas,
    values="valor_liquido",
    index="municipio",
    columns="categoria",
    aggfunc="sum",
    fill_value=0,
    margins=True,
    #margins_name = "Total"
)

df_pivot

categoria           Informática    Móveis  Periféricos        All
municipio
Balneário Camboriú     1799.800     0.000     1124.550   2924.350
Blumenau                  0.000     0.000     1793.340   1793.340
Chapecó                4588.275     0.000        0.000   4588.275
Criciúma                  0.000     0.000     2437.645   2437.645
Florianópolis          7409.810     0.000     1927.835   9337.645
Itajaí                    0.000  3587.724     1379.448   4967.172
Jaraguá do Sul         7409.810     0.000     1139.050   8548.860
Joinville              3626.907     0.000      959.200   4586.107
Lages                     0.000  2339.820     1438.800   3778.620
São José               5024.052     0.000        0.000   5024.052
All                   29858.654  5927.544    12199.868  47986.066

In [58]:
# Outra Pivot: vendedor × canal

df_pivot = pd.pivot_table(
    df_vendas,
    values="valor_liquido",
    index="vendedor",
    columns="canal_venda",
    aggfunc="sum",
    fill_value=0
)

df_pivot

canal_venda    Loja Física    Online  Representante
vendedor
Ana Souza        10997.534  1379.448       3626.907
Bruno Lima        1784.412  6126.675          0.000
Carla Mendes      1793.340     0.000       3778.620
Diego Martins        0.000  8548.860       4588.275
Eduarda Alves     2924.350  2437.645          0.000